// ==========================================================================
// Smart Notes AI - Vercel Serverless Function
// Endpoint: POST /api/summarize
// ==========================================================================

module.exports = async (req, res) => {
    // 1. Enable CORS for local testing if needed, though Vercel handles same-origin by default
    res.setHeader("Access-Control-Allow-Credentials", true);
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.setHeader("Access-Control-Allow-Methods", "GET,OPTIONS,PATCH,DELETE,POST,PUT");
    res.setHeader(
        "Access-Control-Allow-Headers",
        "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version"
    );

    // Handle preflight OPTIONS request
    if (req.method === "OPTIONS") {
        res.status(200).end();
        return;
    }

    // 2. Enforce POST requests
    if (req.method !== "POST") {
        return res.status(455).json({
            error: { message: "Method Not Allowed. Use POST requests." }
        });
    }

    try {
        const { text, type } = req.body;

        // 3. Validation: Empty Note
        if (!text || !text.trim()) {
            return res.status(400).json({
                error: { message: "Notes content cannot be empty." }
            });
        }

        if (text.trim().length < 20) {
            return res.status(400).json({
                error: { message: "Notes must be at least 20 characters long." }
            });
        }

        // 4. Validation: Missing API Key (Environment Variable)
        const apiKey = process.env.GEMINI_API_KEY;
        if (!apiKey || apiKey === "YOUR_API_KEY_HERE") {
            return res.status(500).json({
                error: { message: "Gemini API key is missing on the server. Please check environment variables configuration." }
            });
        }

        // 5. Construct Prompts & Schema for Gemini 1.5 Flash
        let promptText = "";
        const actionType = type || "summarize";

        switch (actionType) {
            case "summarize":
                promptText = `You are a study assistant. Summarize the following study notes in a clean, concise paragraph. Your output must be a JSON object containing a "summary" field (string) with the summarized text.\n\nNotes:\n${text}`;
                break;
            case "mcqs":
                promptText = `You are a study assistant. Generate exactly 5 multiple-choice questions based on the following study notes. For each question, provide 4 distinct options and clearly specify which option is the correct answer. Your output must be a JSON array of objects. Each object in the array must have these keys:\n- "question" (string)\n- "options" (array of 4 strings)\n- "answer" (string, the correct option text)\n\nNotes:\n${text}`;
                break;
            case "flashcards":
                promptText = `You are a study assistant. Generate exactly 5 flashcards based on the following study notes. Each flashcard should test a key concept. Your output must be a JSON array of objects. Each object in the array must have these keys:\n- "question" (string)\n- "answer" (string)\n\nNotes:\n${text}`;
                break;
            default:
                promptText = `You are a study assistant. Summarize the following study notes in a clean, concise paragraph. Your output must be a JSON object containing a "summary" field (string) with the summarized text.\n\nNotes:\n${text}`;
        }

        const apiPayload = {
            contents: [
                {
                    parts: [
                        { text: promptText }
                    ]
                }
            ]
        };

        // 6. Gemini API Call
        const geminiResponse = await fetch(
            `https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
            {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: JSON.stringify(apiPayload)
            }
        );

        // 7. Handle Gemini API Failure
        if (!geminiResponse.ok) {
            const errorDetails = await geminiResponse.json().catch(() => ({}));
            const apiMsg = errorDetails.error?.message || `Gemini API returned status ${geminiResponse.status}`;
            return res.status(geminiResponse.status || 502).json({
                error: { message: `Gemini API error: ${apiMsg}` }
            });
        }

        const responseData = await geminiResponse.json();
        
        // Extract raw JSON string generated by Gemini
        const resultText = responseData.candidates[0].content.parts[0].text;
        let parsedJson;
        
        try {
            let cleanJsonText = resultText.trim();
            if (cleanJsonText.startsWith("```")) {
                cleanJsonText = cleanJsonText.replace(/^```(?:json)?\n?/, "").replace(/\n?```$/, "");
            }
            parsedJson = JSON.parse(cleanJsonText.trim());
        } catch (e) {
            return res.status(500).json({
                error: { message: "Failed to parse JSON response generated by AI." }
            });
        }

        // 8. Return result to client
        return res.status(200).json(parsedJson);

    } catch (error) {
        console.error("Serverless Function Error:", error);
        return res.status(500).json({
            error: { message: `Internal Server Error: ${error.message}` }
        });
    }
};
